### PR TITLE
Add support for AWS Signature v4 request signing

### PR DESCRIPTION
**Pull request by sigpwned**
AWS' ElasticSearch clusters do not support the "typical" transport (port 9300) protocol, instead supporting only the REST (port 9200) protocol. Also, access control isn't very flexible, allowing only IP-based or signature-based approaches.

This makes Jest a lifesaver! It's a great way to work with ElasticSearch's REST API in Java. However, because it does not support signature-based approaches, it's only possible to use Jest with IP-based authentication. This doesn't work for all cloud deployment scenarios, such as those using AWS spot instances.

This pull request adds support for signature-based authentication to Jest. I've added it to the v1.0.2 tag because AWS' ElasticSearch offering is currently at v1.5, so adding to master wouldn't be useful. (I'd be happy to issue another pull request against master if you'd like, though, although it couldn't be used in production until AWS bumps the ElasticSearch version to 2.0.)

I'm currently using the changes in a prototype at work in addition to the tests cases provided in this pull request, which come from Amazon documentation, so the code seems solid. Please shoot any questions my way!

And thank you for building and maintaining Jest! It's a pleasure to use. :)

### CODE REVIEW

**Comment by sigpwned** [comment]
...and apparently I was not thorough in my issues search! (I apparently failed to check through closed issues!) I now see #248 and #264 and the suggested solution aws-signing-request-interceptor. It would be nice to have a fully-integrated solution in Jest with no additional dependencies, but the existing solution works too!

**Comment by marcelalburg** [comment]
I'm interesseted in that too

**Comment by sigpwned** [comment]
> I'm interesseted in that too

Great! Let me know how I can help!

Also, I've just noticed the build failed. I've looked at the details and I'm not sure why:

    The command "openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in secring.gpg.enc -out local.secring.gpg -d" failed and exited with 1 during .

Not knowing anything about the Jest build, I'm not sure where to start tackling that. For what it's worth, the build works on my machine, although any change needs to work in your CI or it's a non-starter. If you can point me in the right direction, I'm happy to put in some legwork to start getting the issue figured out!

**Comment by kramer** [comment]
@sigpwned travis config in the branch was borked and should be fixed now. Though you probably will need to rebase your fork so that travis build for this PR is rerun with new config. I'll try to check the actual content of this PR in the upcoming days when I have the time.

**Comment by sigpwned** [comment]
Understood. Thank you @kramer! I'll give this PR a bump to rebase.

**Comment by marcelalburg** [comment]
Can you show me an example use of this new feature please. And thanks for the PR. I'll test and use it next week.

**Comment by sigpwned** [comment]
@marcelalburg sure thing! Here's how I'm using it in my test at work:

    // You can get all of these AWS details from your AWS setup
    String awsRegion="us-east-1";
    String awsAccessKey="AKIDEXAMPLE";
    String awsSecretKey="wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY";
    JestClientFactory jestFactory=new AWSSigningJestClientFactory(awsRegion, awsAccessKey, awsSecretKey);
    JestClient client=jestFactory.getObject();
    try {
        // Do work here...
    }
    finally {
        client.shutdownClient();
    }

If you have an instance of `AWSCredentials` handy, you can get the access key and secret key from there directly.

Thanks for volunteering to test! Looking forward to hearing about your experience.

**Comment by marcelalburg** [comment]
Thanks. I'll test it at the weekend. i hope this are not valid access key and secret key ;)

**Comment by sigpwned** [comment]
That's great! Thank you for testing! And I hope they're not valid, too -- those are examples from the Amazon Signature v4 documentation! :)

**Comment by sigpwned** [comment]
I've been noodling on this pull request and poking around the other code in Jest, and I think a better design for the AWS signer may look more like an Apache HTTP Client-level solution (e.g. a request intercepter a la aws-signing-request-interceptor) and less like a completely new JestClient (e.g. the current solution). If maintainers would prefer, I'd be happy to refactor this pull request into something that looks more like that -- it should be a fairly simple thing. I don't think most users will mix-and-match HTTP features like proxies and basic auth with the signer -- the details of the signer kind of prevent it, actually -- so it wouldn't unlock more use cases, but it would make the design for AWS signing more orthogonal to the existing approaches. That would basically provide a Java 6-compatible aws-signing-request-interceptor integrated into Jest without adding new dependencies.

**Comment by kramer** [comment]
Why not just fork the [aws-signing-request-interceptor](https://github.com/inreachventures/aws-signing-request-interceptor) and make it java 6 compatible?

**Comment by sigpwned** [comment]
@kramer Certainly an option! And if you'd prefer that approach and would integrate it into Jest master, I'd be happy to do that.

But it feels like less work to adapt this pull request into an Apache request interceptor (the underlying implementation basically works that way anyway) than to make aws-signing-request-interceptor Java 6 compatible and try to remove all its incremental dependencies. 

Does one approach make you more comfortable than the other?

**Comment by kramer** [comment]
*Disclaimer: I know absolutely nothing about AWS and I still have not properly reviewed the changeset here.*

Thinking out of the implementation details my gut feeling would actually be keeping this, aws-interceptor, separate i.e.: not integrate into jest master. A merge to master is somewhat, if you will, permanent i.e. will come with the responsibility and workload of maintaining it in the future and, I believe, there simply is not enough expertise or capacity to do that within this project.

**Comment by sigpwned** [comment]
I went ahead and made the change with the goal of giving you as simple and familiar an approach to signing as I could.

I totally get your point -- commit once, maintain forever.

The good news about this change is that there is more or less zero AWS-specific code involved. The change is 100% all about HTTP request signing, so no AWS-specific knowledge is required to understand or maintain it. The signing procedure is documented [here](http://docs.aws.amazon.com/general/latest/gr/signature-version-4.html) if you're curious, and is pretty standard. These things also tend to "always work" or "always fail" by their design, so there shouldn't be a lot of maintenance to do, ideally.

I'm happy to raise my hand to help field any issues that come up, too, for what that's worth! :)

**Comment by kramer** [comment]
Just had a look at the changeset and was going to ask if we really need `AWSSignatureV4` because it looks common enough to be found as a lib... then I realized it is kinda replicating [aws-signing-request-interceptor](https://github.com/inreachventures/aws-signing-request-interceptor) (correct me if I'm wrong) which feels like a weird thing to do with respect to @thesmith's already existing work :smiley:.

In its current form I am neutral on this PR. 
If there is demand to have it within jest, *and if we have @thesmith's blessing* :stuck_out_tongue:, I'll gladly merge it.

**Comment by thesmith** [comment]
Thanks for notifying me @kramer :)

There were 2 main reasons that having this AWS signer live outside of Jest was compelling enough for me to create aws-signing-request-interceptor and not submit a PR directly to Jest:
1. This isn't Jest specific. The library could be used by other projects.
2. Only a fraction of Jest users will want this, so it's better for the majority of Jest users not to include it.

I think those still hold true so I have a preference for keeping the module separate. If you take a look the issues and PRs that I've handled since I created it, then you can see there's definitely an advantage not to duplicate the effort. There are a lot of 'nuances' in the AWS signing and it would suck if we both had to deal with them individually. I'd also say that they aren't really something that the Jest core team should have to worry about.

So yeah, I'd rather we spent the effort to back-port aws-signing-request-interceptor to Java7 (if that's the issue here) than have to duplicate our efforts to both support AWS API eccentricities (which I don't think should be Jest's problem).

**Comment by kramer** [comment]
I agree with the idea of backporting @thesmith's interceptor project to Java6 and then adding a how-to section in Jest Readme. What do you think @sigpwned ?

**Comment by khundaqji** [comment]
This is a great addition, I have started testing this as well, and will try to give a full feedback once done with it

**Comment by thesmith** [comment]
It might be worth closing this issue and adding something to the README for people to use https://github.com/inreachventures/aws-signing-request-interceptor if possible.

I haven't had any contributions to port to Java6 yet :(

BTW I still think it wouldn't be great to add support for this to Jest, as the need for the AWS signing will go away when AWS allows ES to be run from within a VPC. In that case, Jest would be lumbered with supporting some pointless module.

**Pull request closed without merging**
