### PR TITLE
DeleteByQuery updated to ES 5

### PR DESCRIPTION
**Pull request by fcastillao**

### CODE REVIEW

**Comment by fcastillao** [comment]
Changed the URI from _query to _delete_by_query and changed the  getRestMethodName from "DELETE" to "POST";  to comply with the Elasticsearch 5.x documentation.

**Comment by zhongjiajie** [comment]
Hi, I want to know which version of release have this commit? Did we have CHANGELOG or UPDATE for user to get it? @ferhatsb

**Comment by zhongjiajie** [comment]
> Hi, I want to know which version of release have this commit? Did we have CHANGELOG or UPDATE for user to get it? I can not get from our REPO @ferhatsb

I finally find out in master commit

**Comment by johntremonton** [comment]
To be honest, I didn't even make it. I found it on my computer. I am not
very good at programming, design, etc. But I kept getting hacked so I
started learning.....slowly. Can you explain to me exactly what it does,
and how can it be used??

Thank you

John Thornton

**Pull request merged**
