### PR TITLE
Fix #412 - close processed http response stream 

### LINKED ISSUE #412: CloseableHttpResponse is not closed in JestHttpClient.execute()
Hallo,

I think that in `JestHttpClient#execute()` is called `JestHttpClient#executeRequest,` returning `org.apache.http.client.methods.CloseableHttpResponse`, but there is not any call of `java.io.Closeable#close` on this instance, I think.

Are you sure, is it ok?

Best regards,

Michal

### PR DESCRIPTION
**Pull request by michalsida**
Fix #412 - could be easier with Java 7

### CODE REVIEW

**Comment by gsmet** [comment]
@ferhatsb depending on your opinion on https://github.com/searchbox-io/Jest/issues/423 , we might include it or use a try with resources.

Anyway, it looks like an important fix.

**Comment by ferhatsb** [comment]
Lets accept.

**Comment by michalsida** [comment]
Is any plan for releasing next version with this merged fix? We have some production problem, which can be affected with this bug and we would prefer to use released version from public repositories.

**Comment by gsmet** [comment]
@michalsida yes, I discussed with @ferhatsb the other day and he's planning on releasing a version soon. There are a few other things to merge before that though.

**Pull request merged**
