### PR TITLE
Making JEST work with 2.0.0 beta1

### PR DESCRIPTION
**Pull request by andrejserafim**
Hi,

I'm on a road of trying jest out with ES 2.0.0 beta1. There's quite a lot of changes there, so I'm first trying to compile it - I recon I'm a good way into that, but work still ongoing.

Before I go too far, I wanted to start a conversation if this work is required? Is anyone else trying to do it? Am I doing it right? - please bear with me, I'm a little new to github and contributing to opensource projects.

Thanks

### CODE REVIEW

**Comment by kramer** [comment]
Hi @andrejserafim 

That's quite the changeset there, I appreciate the effort and will have a look when I have the time - hopefully this weekend.

> if this work is required?

Well, yes at some point we would want Jest to work with ES v2. Only thing to watch out is that the current version is beta and a lot of things may change in the final release possibly meaning some wasted effort.

>  Is anyone else trying to do it?

No, not that I know of.

> Am I doing it right?

Will give feedback after going through the changes :)
Just this tiny comment so far: you could maybe create this/next PR against a `es_2` branch instead of `master`.

**Comment by andrejserafim** [comment]
On the branches, I don't think I could create a new one - maybe I just missed the option somewhere. And now I don't see a way to change it on the pull request.

**Comment by andrejserafim** [comment]
Well, looks like all the tests are passing. I'm going to stop working on this for a bit. So let me know when you've had a chance to have a look at this.

In terms of branches, a little googling shows that if you create a new branch where this should go, I can always create a new pull request referencing this one. At least that's the way I understood it.

Thanks

**Comment by kramer** [comment]
Hey,

Checked out the changes just now, sorry for the delay. Great work there, thanks a lot for your contribution.

Just one thing: in `AbstractActionTest` you have `//TODO: This cannot be derived from the result anymore`; could you elaborate on that please?

As for the branching you're right, I forgot that. I'll be manually pulling in the changes into a new branch, no worries.

**Comment by andrejserafim** [comment]
That's not my TODO, rathen I've fixed a typo in it:
-    //TODO: This cannot be derived fron the result anymore
+    //TODO: This cannot be derived from the result anymore

The only tricky point I can think of was the "/" in the URL @ https://github.com/searchbox-io/Jest/pull/246/files#diff-76a049c38322c67dafd605786d6f63a3R40, no idea what's going on there.

Thanks for accepting!

**Comment by kramer** [comment]
Yeah looks like a leftover TODO, sorry :)

I noticed the special character problem, let's see how the issue you opened turns out.

**Pull request merged**
