### PR TITLE
Update by query

### LINKED ISSUE #446: _update_by_query not supporterd
Please add it

### PR DESCRIPTION
**Pull request by gilbode**
Fixes #446.  Rebased pr #453 onto master.

### CODE REVIEW

**Comment by lior-k** [comment]
@gilbode ?

**Comment by gilbode** [comment]
@lior-k - not sure what you're asking but I'm not a committer so if you're asking why this isn't merged I can't answer that

**Comment by lior-k** [comment]
Maybe due to the "1 failing check"

**Comment by gilbode** [comment]
@lior-k the failures have nothing to do w/ this PR, I rebased and am now getting failures that there are other PRs for.

**Comment by lior-k** [comment]
@joschi - can you please help with this merge?

**Comment by joschi** [comment]
@lior-k See #538 and #540.

**Comment by lior-k** [comment]
Thanks for merging @ferhatsb

**Pull request merged**
