### PR TITLE
Add reindex API support (fix #436)

### LINKED ISSUE #436: Add reindex API
[reindex API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html) is a powerful new elasticsearch feature since version 2.3.
This would be great to add support for this feature in Jest API !

### PR DESCRIPTION
**Pull request by fbaligand**

### CODE REVIEW

**Comment by fbaligand** [comment]
@searchbox-io
Could you review this PR ?

**Comment by ferhatsb** [comment]
Hi @fbaligand 

Is it possible to add an integration test ? So far LGTM.

**Comment by fbaligand** [comment]
Hi @ferhatsb,
Actually, I tried to. 
But it requires to upgrade elasticsearch dependency to 2.3.0 at least. 
And when I ran tests, it fails :(

**Comment by fbaligand** [comment]
@ferhatsb,
To be more clear, if I upgrade elasticsearch dependency version to 2.3.0 in Jest parent POM, some existing tests don't compile, some other fail at execution time.
That's why I abandoned the idea to make an integration test for reindex API.

**Comment by ferhatsb** [comment]
I will check this next week to move 2.3-2.4 before going for 5.0

**Comment by fbaligand** [comment]
Nice news !

**Comment by fbaligand** [comment]
Hi @ferhatsb,
Do you still plan to upgrade Jest elasticsearch dependency to 2.3.0 ? 
If so, when do you plan to do it ?

**Comment by ferhatsb** [comment]
Just pushed with ES 2.4.3 with less hair.

You need to add reindex module as maven dependency( see groovy lang) and apply it as plugin at integration test (see scripted tests).

**Comment by fbaligand** [comment]
Hi, 
it's strange, because you speak about ES 2.4.3.
However, in pom.xml, I see elasticsearch.version=2.4.1

**Comment by ferhatsb** [comment]
well 2.4.1 it is, was aimed 2.4.3 though, anyway it is very simple change

**Comment by fbaligand** [comment]
OK.
Anyway, this is quiet the same :)
That said, I am annoyed : travis-ci build failed because of a bad version plugin dependency :
```
The project io.searchbox:jest-parent:2.0.5-SNAPSHOT (/home/travis/build/searchbox-io/Jest/pom.xml) has 1 error

[ERROR]     Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.7 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.7: Could not transfer artifact org.sonatype.plugins:nexus-staging-maven-plugin:pom:1.6.7 from/to central (https://repo.maven.apache.org/maven2): Access denied to: https://repo.maven.apache.org/maven2/org/sonatype/plugins/nexus-staging-maven-plugin/1.6.7/nexus-staging-maven-plugin-1.6.7.pom , ReasonPhrase:Forbidden. -> [Help 2]
```

**Comment by ferhatsb** [comment]
Ensure, code is sync with origin, changed version from 2.0.5 to 2.4.0 at master

**Comment by fbaligand** [comment]
Ok, after a git rebase, it works better !

**Comment by fbaligand** [comment]
Hi @ferhatsb 

I tried to add my integration test, but big surprise : the embedded elasticsearch instance for integrations tests don't recognize `_reindex` as an API but considers it like an index...

I get this error, while trying to call reindex : 
``` json
{
   "error": {
      "root_cause": [
         {
            "type": "invalid_index_name_exception",
            "reason": "Invalid index name [_reindex], must not start with '_'",
            "index": "_reindex"
         }
      ],
      "type": "invalid_index_name_exception",
      "reason": "Invalid index name [_reindex], must not start with '_'",
      "index": "_reindex"
   },
   "status": 400
}
```

Of course, I believe first that was a bug in my code, but :
- If I execute the same code on a standalone elasticsearch 2.4.1 instance, it works
- I truly checked that started embedded instance is a 2.4.1 version
- during the test, I tried to make the same reindex call from sense, and it raises same error.
- endly, all other jest integration tests work

Have you any idea of how to make reindex API recognized by elasticsearch embedded instance ?

**Comment by fbaligand** [comment]
@ferhatsb 
If you want that I commit integration test so that you can test for yourself, tell me.

**Comment by ferhatsb** [comment]
Please commit to your branch, I can check it.

**Comment by fbaligand** [comment]
@ferhatsb 
I just committed `ReindexIntegrationTest` class in jest module.
And travis-ci reproduce the error I get.

Thanks to check it ! That's much appreciable !

**Comment by ferhatsb** [comment]
Please see my changes, merged.

**Comment by fbaligand** [comment]
Nice ! 
Thanks a lot for the fix !
I saw that the main problem is that elasticsearch embedded test server needed an extra dependency.

**Comment by ferhatsb** [comment]
Indeed, embedded ES does not loading modules as regular distribution, also in tests it is required to override loaded plugins.
Well, now works like a charm, thanks for your contribution.

**Comment by fbaligand** [comment]
It was a pleasure !
And thanks for your help !
When do you plan to make next release ?

**Comment by fbaligand** [comment]
@ferhatsb 
I detected a duplicate maven dependency in jest/pom.xml.
So I just created a PR to fix it : #445

**Comment by ferhatsb** [comment]
I may need to work on issues overall and see if we can have quick wins.
Guess we can make a release by first week of 2017.

**Pull request merged**
