### PR TITLE
Added support for the update_by_query action

### PR DESCRIPTION
**Pull request by lior-k**
Please approve this PR for supporting the [update_by_query REST action](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/docs-update-by-query.html)

### CODE REVIEW

**Comment by lior-k** [comment]
When is this going to be merged?

**Comment by lior-k** [comment]
Please merge this

**Comment by bitsofinfo** [comment]
+1

**Comment by ferhatsb** [comment]
Does this works with master with ES 5 ?

**Comment by gilbode** [comment]
I've created a new PR based on this one that works on master w/ ES 5.

**Comment by ferhatsb** [comment]
Missed this but merged another, can close that one.

**Pull request closed without merging**
