### PR TITLE
implement Children Aggregation support

### PR DESCRIPTION
**Pull request by marcelalburg**
implement Children Aggregation support 
Ticket: #534

### CODE REVIEW

**Comment by marcelalburg** [comment]
@ferhatsb @joschi : It is possible to merge my pul requests and maybe publish a new version of jest ? There are more good PR in that project and the last release is from may this year.

Thanks

**Comment by marcelalburg** [comment]
Thanks @ferhatsb @joschi  for acting so fast. It is possible to upload the new release to the mvn repositories ? it would help us so much and make our build process much easier. Thanks a lot.

**Comment by ferhatsb** [comment]
Release should be synced to central repo automatically... did it ?

**Comment by marcelalburg** [comment]
@ferhatsb : I don't know if it happen automatically, but i don't see it in mvncentral nor mvnrepository.

https://mvnrepository.com/artifact/io.searchbox/jest
https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.searchbox%22%20AND%20a%3A%22jest%22

**Pull request merged**
